AWSTemplateFormatVersion: '2010-09-09'
Description: 'runvoy - releases bucket with multi-region replication (public-read)'

Parameters:
  ProjectName:
    Type: String
    Default: runvoy
    Description: Name prefix for resources

Resources:

  # S3 bucket for releases (regional)
  # Deploy this template to all regions via CloudFormation StackSets
  # After all buckets exist, replication can be configured via a separate template
  ReleasesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-releases-${AWS::Region}'
      # Enable versioning for replication and release history
      VersioningConfiguration:
        Status: Enabled
      # Enable public access for releases
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-releases-${AWS::Region}'
        - Key: Application
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: 'cloudformation'
        - Key: Owner
          Value: 'runvoy devs'

  # Bucket policy to allow public read access to objects
  ReleasesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ReleasesBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action:
              - s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${ReleasesBucket}/*'

Outputs:
  BucketName:
    Description: Regional S3 bucket name for releases
    Value: !Ref ReleasesBucket
    Export:
      Name: !Sub '${ProjectName}-releases-${AWS::Region}'

  BucketArn:
    Description: S3 bucket ARN
    Value: !GetAtt ReleasesBucket.Arn
    Export:
      Name: !Sub '${ProjectName}-releases-arn-${AWS::Region}'

  BucketURL:
    Description: S3 URI for Lambda function code (use in CloudFormation)
    Value: !Sub 's3://${ReleasesBucket}/'
    Export:
      Name: !Sub '${ProjectName}-releases-url-${AWS::Region}'

  BucketHTTPSURL:
    Description: HTTPS URL for public access to releases
    Value: !Sub 'https://${ReleasesBucket}.s3.${AWS::Region}.amazonaws.com/'
    Export:
      Name: !Sub '${ProjectName}-releases-https-${AWS::Region}'


