# This workflow generates documentation using gomarkdoc and uploads it as an artifact.
name: Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  docs:
    name: Generate and upload documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Go environment
        uses: ./.github/actions/setup-go

      - name: Install gomarkdoc
        run: go install github.com/princjef/gomarkdoc/cmd/gomarkdoc@latest

      - name: Generate documentation
        run: gomarkdoc ./... --output gomarkdoc

      - name: Push documentation to ORAS registry
        uses: runvoy/ghcr-artifacts-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: upload
          name: runvoy-docs
          tag: latest
          files: gomarkdoc
