name: Tests and Coverage (Go)

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  tests:
    name: Tests and Coverage (Go)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Go environment
        uses: ./.github/actions/setup-go

      - name: Add just
        uses: extractions/setup-just@v3

      - name: Generate coverage profile
        run: just gen-coverage

      - name: Check coverage threshold
        uses: vladopajic/go-test-coverage@v2
        with:
          config: .testcoverage.yml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          files: ./coverage.out
